name: chatz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.2
  firebase_auth: ^3.6.2
  firebase_storage: ^10.3.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0
  provider: ^6.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/user-cuate.png
     - assets/user-pana.png
     - assets/user-rafiki.png
     - assets/avatar.png
     - assets/arrow.png
     - assets/login-bro.png
     - assets/avatar-2.png

